### ISSUE TITLE
Improve art

### ISSUE THREAD

**Issue by tnibert** [tnibert/Kill-The-Aliens#6]
As of right now the artwork is kind of thrown together for the purpose of getting the game made.  If someone who is a better artist than I would like to make some art for the game, it would be greatly appreciated.  If you make an image file of the same dimensions as the sprite image files with the same file name, it should just plug right into the program.  The opening and closing screens are especially bad, and the game map is just a bunch of green dots on a black background.

In _theory_ you can adjust the sprite image sizes and it will work without any code modification.  The exception to this is the explosion image which is split into frames.  The width of each frame is defined by the xstep parameter of the toframes() function in obj.py (currently 120 pixels, should be put into it's own variable).  There is code to for sprite animation (eg like the explosion), but it will need more code added to implement it, but it's definitely not a huge step if desire is there.

We can extend it as much as we want to make it look cool and have special effects and all that.  Ideas are more than welcome.

**Comment by MagykalMystique** [comment]
I am a fairly good artist, and I would be willing to help, that is if you're still looking for it.

**Comment by tnibert** [comment]
Yeah, totally!  Please do :)  If you have any questions about dimensions or integrating anything into the code, just ask.  All of the current art is just in the same directory as the code.  I'm a bit new to collaboration on github, so I suppose when it's done try to attach it to a pull request.  Just from a quick look, pull requests seem pretty code oriented, so if that doesn't work, just let me know and we'll get it in the package.

**Comment by MagykalMystique** [comment]
Hello, I have finished the new art. I tried to keep everything within the same size as the original pictures to help with the collision events, but I'm not certain how well I did in that regard. You won't need to worry about infringement possibilities now, as long as you credit me for the art. I even did the handwriting on the title screens and such by hand so there shouldn't be any issues of font copyrights and such. (I've done calligraphy before if you were wondering). I hope you are pleased with the new designs. If there are any issues let me know.

[ImprovedArt.zip](https://github.com/tnibert/Kill-The-Aliens/files/593461/ImprovedArt.zip)

**Comment by tnibert** [comment]
That's cool as hell O_O  Thanks!  

I've only seen a few issues.  Only one is art related, which is that at the map change over (e.g. when the map ends and loops back over connecting to the bottom), there is a defined line/color change where that happens.  If you could make it blend that would be super awesome.  

The other two issues I need to adapt the code.  One is that when I designed the explosions for the boss, I appended a black square as the last frame to take chunks out of the boss.  Worked great for a black background, but now I need to make it a transparent square.  Should just be a change of one parameter in one line.

Then there's an issue of where the boss is shooting the bullets from.  Before, the space invader had "arms" that kind of looked like guns, so I lined the bullets up with them, but now the bullets seem like they are coming out of the air.  I was thinking it would be cool to make the boss shoot a laser beam out of its mouth instead.  It's a bit of a bigger change, but it should all be in the Boss class' methods.  Need to change AI, positioning of shot, probably making a beam object and adding associated collisions, and an image to go along.  I think it would be pretty cool that way though.  Maybe I'll make a smaller bullet alignment fix first and make the beam thing a larger goal.

Then there's the issue of github not detecting image changes >_> not the business, may have to completely delete the current images from the repository and upload the new ones.  But that is neither here nor there.

Great work, I really like it.  If you would like to jump into the code at all, you're more than welcome to.  That transparent square thing could be a good start.  If you'd like any guidance on the code structure or anything, I'm available by email (it's in my profile).  I'm not sure if you'd be interested in something like that, but yeah, if you want to just make a branch.  Let me know your feedback.

**Comment by MagykalMystique** [comment]
:) I'm glad you're pleased with the art. I'll try to work on the map background. I have done some python, but am unfamiliar with the pygame module. I think it'd be interesting to try playing with the code, but do know that I'm far from being an expert... forewarning... lol
However if I never try to do things outside of what I know with a surety or things that are somewhat different, how will I ever improve more fully? 
I came here on GitHub to hopefully get more experience with coding actual projects rather than just reading about it, and I hope you will be alright with my not already knowing all there is to know. Of course though considering that I'm only 16, it's probably a good thing that I don't already know everything. If I did I think that'd be somewhat worrisome lol

**Comment by tnibert** [comment]
GitHub is good for that.  If you muck it up, you can always just revert it back.  Main thing is just make sure you're always working in a branch, never push to master.

As far as pygame, it's python bindings for another library called SDL.  We actually aren't using it that much.  Pretty much just to create our window, handle our input, provide us with bitmap objects, and blit (render) to the screen.  All of that stuff happens in killthealiens.py.  We have a file obj.py that contains the classes for player, enemies, boss, bullet, etc.  Think killthealiens.py as being the main game loop and gameplay logic and obj.py as being our own tools that we've created for usage in killthealiens.py.  So updates of positioning, (most of) collision, etc are all handled in house.  Think of the screen as a graph, with (0,0) being in the top left and the largest number coordinates being the bottom right corner.

If you want to just completely screw around with the code in any way you want, make your own fork of the repository and then any changes wont affect this project.  If you want to try to implement a specific feature create a branch.
Process would be (from command line):
git clone https://github.com/tnibert/Kill-The-Aliens/
cd Kill-The-Aliens/
git checkout -b newbranchname
Create your commits:
git add changedfile1 changedfile2 etc
git commit -m "description of changes"
The first time you push this branch to the repository you do:
git push -u origin newbranchname

After that you can just use
git checkout newbranchname
to go to your branch and
git push origin newbranchname
to push to repository

If you finish implementing a change and want it merged into the master branch, just go to the branch on github and make a pull request.  I'll review it and either give feedback or merge it in.

I was hoping when I put this up here that it could kind of take on a life of its own and get a few people just bringing what they had to the table to make this thing as bad ass as it could be.  Learning to work with someone else's code is definitely a skill, and it's a big step.  Just try to get a feel for the conventions of the code and the order and flow with which it executes.  Make a fork, make modifications, break things, see how a change in one place affects other places, etc.

As I said, if you have any questions, email.  I'm more than happy to explain how it works.  Maybe start with trying to integrate the art into the code, two fairly simple modifications would be
A) making transparent squares for pieces taken out of the boss at the end and
B) removing the empty space on the sides of the new boss image and adjusting the bullet spawning code (coordinates, make sure boss isn't shooting himself) so that the bullets come out of a more logical place (eyes? mouth? nose? tentacles?), confirming that removing the empty space doesn't make the whole thing come crashing down
C) changing the file names for the images (and in the code) so we can upload them to github and use them

You could also always ask your teacher for insight into it as well, if they're anything like my CS teachers they'd be thrilled about something like this.

Sorry for the mouthful, but yeah, if it is something you would like to do, hopefully that gives you a bit of a starting point.

**Comment by MagykalMystique** [comment]
Okay here is the map.png with the implemented changes. Hopefully it'll have a smoother transition now when the image loops :)
![map](https://cloud.githubusercontent.com/assets/22778232/20550124/ef03a55c-b0ef-11e6-949e-e9e25ddf8270.png)

**Comment by tnibert** [comment]
Integrated new art with pull request #18 :)
